/*
 * Tool_Assembler.README_builder.c  (binary: shakti-readme-assembler)
 *
 * Auto assembler for Shakti tool-family READMEs.
 * Walks a tools directory; for every family directory (a subdirectory
 * holding at least one .c source) it emits a structurally identical
 * README.md in the canonical four-section format:
 *
 *   # Family_Name
 *   FILE SETS (in order)      — enumerated Firstname.Lastname stems
 *   SCRIPT FILES (in order)   — sorted directory listing, README.md
 *                               always present (it is being written)
 *   ## I. INTRODUCTION        — carried over from existing README,
 *                               else {[tool_family].[introduction]}
 *   ## II. REQUIREMENTS       — carried over, else placeholder
 *   ## III. RUNNING NOTES     — carried over, else placeholder
 *   ## IV. REFERENCES         — auto-listed from tests/ contents
 *
 * Laws honored:
 *   deterministic  — same tree in, same bytes out; sorted listings;
 *                    no timestamps; non-ASCII written as explicit bytes
 *   nothing ram blind — fixed static buffers, every overflow is a
 *                    WARN-truncate or a bench, never a silent loss
 *   failures bench — unreadable dir: refuse (2); no families: bench (3);
 *                    output overflow: bench (3); check drift: exit 4
 *   never lose    — hand-written I/II/III bodies are extracted verbatim
 *                    and carried into the regenerated skeleton
 *
 * Usage: shakti-readme-assembler TOOLS_DIR [check] [verbose]
 *   check    do not write; compare generated bytes to existing READMEs
 *   verbose  trace every step to stdout
 *
 * C99 strict: cc -std=c99 -pedantic -Wall -Wextra -Werror -O2
 */

#define _POSIX_C_SOURCE 200809L

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <dirent.h>
#include <sys/stat.h>

#define MAXF    1024            /* entries per directory            */
#define MAXN    256             /* one entry name                   */
#define MAXP    1200            /* full path                        */
#define MAXSEC  65536           /* one carried-over section body    */
#define MAXOUT  262144          /* one generated README             */
#define MAXLINE 4096            /* one input line                   */
#define MAXT    512             /* tool families per tools dir      */

#define EM_DASH "\xE2\x80\x94"  /* em dash, explicit bytes          */

typedef struct {
    char name[MAXN];
    int  isdir;
} dent_t;

static int  g_verbose = 0;
static int  g_check   = 0;

static char   g_out[MAXOUT];    /* generated README under construction */
static size_t g_olen = 0;

static dent_t g_de[MAXF];       /* main directory listing            */
static dent_t g_de2[MAXF];      /* scratch listing (peeks, tests/)   */

static char g_fams[MAXT][MAXN]; /* qualified + candidate family names */

/* ------------------------------------------------------------------ */

static void bench(const char *why)
{
    fprintf(stderr, "BENCH: %s\n", why);
    exit(3);
}

static int join3(char *dst, size_t cap, const char *a, const char *b)
{
    int n = snprintf(dst, cap, "%s/%s", a, b);
    if (n < 0 || (size_t)n >= cap) return -1;
    return 0;
}

static void out_add(const char *s)
{
    size_t n = strlen(s);
    if (g_olen + n >= MAXOUT)
        bench("generated README over MAXOUT bytes");
    memcpy(g_out + g_olen, s, n);
    g_olen += n;
    g_out[g_olen] = '\0';
}

static void copy_name(char *dst, const char *src)
{
    size_t n = strlen(src);
    if (n >= MAXN)
        bench("entry name over MAXN bytes");
    memcpy(dst, src, n + 1);
}

/* ------------------------------------------------------------------ */
/* Master printout: one searchable file at the tools-dir root.         */

#define MAXMAS 1048576          /* master printout cap              */

static char   g_master[MAXMAS];
static size_t g_mlen = 0;

static int g_viol = 0;          /* naming-law violations            */
static int g_fam_ok[MAXT];      /* pass-A validation results        */

static void mas_addn(const char *s, size_t n)
{
    if (g_mlen + n >= MAXMAS)
        bench("master printout over MAXMAS bytes");
    memcpy(g_master + g_mlen, s, n);
    g_mlen += n;
    g_master[g_mlen] = '\0';
}

static void mas_add(const char *s)
{
    mas_addn(s, strlen(s));
}

/* ------------------------------------------------------------------ */
/* Strict naming law (Shakti_Shell calls everything by rule):          */
/*   family dir  First_Name-Second_Name — capital first letters,       */
/*               _ between words, exactly one dash                     */
/*   scripts     <First>.<Second>.c — every .c shares the first name   */
/*   binary      shakti-<second lowercased, _ becomes ->               */
/*   single-file tools live at the root: shakti-<lowercase-hyphen>     */

static int valid_words(const char *s, size_t n)
{
    size_t i;
    int ws = 1;                 /* at a word start */

    if (!n) return 0;
    for (i = 0; i < n; i++) {
        char c = s[i];
        if (c == '_') {
            if (ws) return 0;
            ws = 1;
            continue;
        }
        if (ws) {
            /* capital first letter of the name; words after _ may
               start lowercase (Template_builder per Tyler's example) */
            if (i == 0 && (c < 'A' || c > 'Z')) return 0;
            if (!((c >= 'A' && c <= 'Z') || (c >= 'a' && c <= 'z')))
                return 0;
            ws = 0;
        } else if (!((c >= 'A' && c <= 'Z') ||
                     (c >= 'a' && c <= 'z') ||
                     (c >= '0' && c <= '9'))) {
            return 0;
        }
    }
    return !ws;
}

static int valid_single(const char *s)
{
    size_t i;
    if (strncmp(s, "shakti-", 7) != 0) return 0;
    if (!s[7]) return 0;
    for (i = 7; s[i]; i++) {
        char c = s[i];
        if (!((c >= 'a' && c <= 'z') ||
              (c >= '0' && c <= '9') || c == '-'))
            return 0;
    }
    return 1;
}

/* "<first>." prefix, built without snprintf (truncation-proof). */
static size_t first_prefix(const char *fam, char *dst, size_t cap)
{
    const char *dash = strchr(fam, '-');
    size_t a = (size_t)(dash - fam);

    if (a + 2 > cap)
        bench("family name over cap");
    memcpy(dst, fam, a);
    dst[a] = '.';
    dst[a + 1] = '\0';
    return a + 1;
}

static void expected_script(const char *fam, char *dst, size_t cap)
{
    const char *dash = strchr(fam, '-');
    size_t a = (size_t)(dash - fam);
    size_t b = strlen(dash + 1);

    if (a + 1 + b + 2 >= cap)
        bench("family name over cap");
    memcpy(dst, fam, a);
    dst[a] = '.';
    memcpy(dst + a + 1, dash + 1, b);
    memcpy(dst + a + 1 + b, ".c", 3);
}

static void expected_binary(const char *fam, char *dst, size_t cap)
{
    const char *dash = strchr(fam, '-') + 1;
    size_t w = 0;

    const char *pre = "shakti-";
    while (*pre) {
        if (w + 1 >= cap) bench("binary name over cap");
        dst[w++] = *pre++;
    }
    while (*dash) {
        char c = *dash++;
        if (w + 1 >= cap) bench("binary name over cap");
        if (c == '_') c = '-';
        else if (c >= 'A' && c <= 'Z') c = (char)(c + 32);
        dst[w++] = c;
    }
    dst[w] = '\0';
}

static int path_exists(const char *path)
{
    struct stat st;
    return stat(path, &st) == 0;
}

static int list_dir(const char *path, dent_t *out, int cap);
static int is_c_source(const char *s);

/* Pass-A validation. Returns 0 ok, 1 violation, 2 not a family. */
static int check_family(const char *tools_dir, const char *fam)
{
    char fdir[MAXP], p[MAXP], exp[MAXP], pre[MAXN];
    const char *dash;
    int m, j, has_c = 0, bad = 0;

    if (join3(fdir, sizeof fdir, tools_dir, fam) != 0)
        bench("family path over MAXP");
    m = list_dir(fdir, g_de2, MAXF);
    if (m < 0) {
        printf("SKIP %s: cannot list\n", fam);
        return 1;
    }
    for (j = 0; j < m; j++)
        if (!g_de2[j].isdir && is_c_source(g_de2[j].name)) has_c = 1;
    if (!has_c) {
        if (g_verbose)
            printf("skip  %s  (no .c source — not a tool family)\n", fam);
        return 2;
    }

    dash = strchr(fam, '-');
    if (!dash || strchr(dash + 1, '-') ||
        !valid_words(fam, (size_t)(dash - fam)) ||
        !valid_words(dash + 1, strlen(dash + 1))) {
        printf("SKIP %s: naming law — dir must be First_Name-Second_Name,"
               " capital first letters, _ between words\n", fam);
        return 1;
    }

    expected_script(fam, exp, sizeof exp);
    if (join3(p, sizeof p, fdir, exp) != 0)
        bench("script path over MAXP");
    if (!path_exists(p)) {
        printf("SKIP %s: naming law — script %s missing\n", fam, exp);
        bad = 1;
    }

    first_prefix(fam, pre, sizeof pre);
    for (j = 0; j < m; j++) {
        if (g_de2[j].isdir || !is_c_source(g_de2[j].name)) continue;
        if (strncmp(g_de2[j].name, pre, strlen(pre)) != 0) {
            printf("SKIP %s: naming law — %s does not start with %s\n",
                   fam, g_de2[j].name, pre);
            bad = 1;
        }
    }

    expected_binary(fam, exp, sizeof exp);
    if (join3(p, sizeof p, fdir, exp) != 0)
        bench("binary path over MAXP");
    if (!path_exists(p)) {
        printf("SKIP %s: naming law — binary %s missing\n", fam, exp);
        bad = 1;
    }
    return bad;
}

static int cmp_dent(const void *a, const void *b)
{
    return strcmp(((const dent_t *)a)->name, ((const dent_t *)b)->name);
}

/* List one directory into out[], sorted by name. Returns count or -1. */
static int list_dir(const char *path, dent_t *out, int cap)
{
    DIR *d = opendir(path);
    struct dirent *e;
    int n = 0;

    if (!d) return -1;
    while ((e = readdir(d)) != NULL) {
        char p[MAXP];
        struct stat st;
        int nn;

        if (!strcmp(e->d_name, ".") || !strcmp(e->d_name, ".."))
            continue;
        if (n >= cap) {
            closedir(d);
            bench("directory entries over MAXF");
        }
        nn = snprintf(out[n].name, MAXN, "%s", e->d_name);
        if (nn < 0 || nn >= MAXN) {
            fprintf(stderr, "WARN: name over %d bytes in %s, skipped: %.32s...\n",
                    MAXN, path, e->d_name);
            continue;
        }
        out[n].isdir = 0;
        if (join3(p, sizeof p, path, e->d_name) == 0 &&
            stat(p, &st) == 0 && S_ISDIR(st.st_mode))
            out[n].isdir = 1;
        n++;
    }
    closedir(d);
    qsort(out, (size_t)n, sizeof(dent_t), cmp_dent);
    return n;
}

static int is_c_source(const char *s)
{
    size_t n = strlen(s);
    return n > 2 && s[n - 2] == '.' && s[n - 1] == 'c';
}

/* ------------------------------------------------------------------ */
/* Extract one "## <title>" section body from an existing README.      */
/* Returns 1 if found; body copied to dst with leading/trailing blank  */
/* lines stripped. Streaming fgets, fixed buffer, never loads file.    */

static int blank_span(const char *s, size_t n)
{
    size_t i;
    for (i = 0; i < n; i++)
        if (s[i] != ' ' && s[i] != '\t') return 0;
    return 1;
}

static void trim_body(char *s)
{
    char *p = s;
    size_t n;

    for (;;) {                          /* leading blank lines */
        char *nl = strchr(p, '\n');
        size_t L = nl ? (size_t)(nl - p) : strlen(p);
        if (!blank_span(p, L)) break;
        if (!nl) { *s = '\0'; return; }
        p = nl + 1;
    }
    if (p != s) memmove(s, p, strlen(p) + 1);

    n = strlen(s);                      /* trailing blank tail  */
    while (n && (s[n - 1] == '\n' || s[n - 1] == ' ' || s[n - 1] == '\t'))
        s[--n] = '\0';
}

static int extract_section(const char *path, const char *title,
                           char *dst, size_t cap)
{
    FILE *f = fopen(path, "r");
    static char line[MAXLINE];
    char want[MAXN];
    int capturing = 0, found = 0;
    size_t len = 0;

    if (!f) return 0;
    dst[0] = '\0';
    snprintf(want, sizeof want, "## %s", title);

    while (fgets(line, sizeof line, f) != NULL) {
        size_t L = strlen(line);

        if (L && line[L - 1] != '\n' && !feof(f)) {
            int c;
            fprintf(stderr, "WARN: line over %d bytes in %s, truncated\n",
                    MAXLINE, path);
            while ((c = fgetc(f)) != EOF && c != '\n') { }
        }
        while (L && (line[L - 1] == '\n' || line[L - 1] == '\r'))
            line[--L] = '\0';

        if (L >= 3 && line[0] == '#' && line[1] == '#' && line[2] == ' ') {
            if (capturing) break;
            if (strcmp(line, want) == 0) { capturing = 1; found = 1; }
            continue;
        }
        if (capturing) {
            if (len + L + 1 >= cap) {
                fprintf(stderr, "WARN: section %s over %d bytes in %s, truncated\n",
                        title, MAXSEC, path);
                break;
            }
            memcpy(dst + len, line, L);
            len += L;
            dst[len++] = '\n';
            dst[len] = '\0';
        }
    }
    fclose(f);
    if (!found) return 0;
    trim_body(dst);
    return 1;
}

/* ------------------------------------------------------------------ */
/* Build the canonical README for one family into g_out.               */

static const char *SEC_TITLE[3] = {
    "I. INTRODUCTION",
    "II. REQUIREMENTS",
    "III. RUNNING NOTES"
};

static const char *SEC_PH[3] = {
    "{[tool_family].[introduction]}",
    "{[tool_family].[requirements]}",
    "{[tool_family].[running_notes]}"
};

/* Ensure README.md appears in the sorted script listing (it is the    */
/* file being written, so it exists by definition). Returns count.     */
static int with_readme(dent_t *de, int n)
{
    int i, pos;

    for (i = 0; i < n; i++)
        if (!de[i].isdir && !strcmp(de[i].name, "README.md"))
            return n;
    if (n >= MAXF)
        bench("directory entries over MAXF (README inject)");
    pos = n;
    for (i = 0; i < n; i++)
        if (strcmp(de[i].name, "README.md") > 0) { pos = i; break; }
    memmove(&de[pos + 1], &de[pos], (size_t)(n - pos) * sizeof(dent_t));
    copy_name(de[pos].name, "README.md");
    de[pos].isdir = 0;
    return n + 1;
}

static int emit_family(const char *tools_dir, const char *fam)
{
    char fdir[MAXP], rpath[MAXP], tdir[MAXP];
    static char sec[MAXSEC];
    char num[64];
    int n, i, t, sets, k, tn;

    if (join3(fdir, sizeof fdir, tools_dir, fam) != 0)
        bench("family path over MAXP");
    n = list_dir(fdir, g_de, MAXF);
    if (n < 0) {
        fprintf(stderr, "WARN: cannot list %s, skipped\n", fdir);
        return 0;
    }
    n = with_readme(g_de, n);

    g_olen = 0;
    g_out[0] = '\0';

    /* header + file sets */
    out_add("# ");
    out_add(fam);
    out_add("\n\nFILE SETS (in order):\n");
    sets = 0;
    for (i = 0; i < n; i++)
        if (!g_de[i].isdir && is_c_source(g_de[i].name)) sets++;
    if (!sets) {
        out_add("(none)\n");
    } else {
        k = 0;
        for (i = 0; i < n; i++) {
            char stem[MAXN];
            size_t sl;
            if (g_de[i].isdir || !is_c_source(g_de[i].name)) continue;
            k++;
            snprintf(num, sizeof num, "%d of %d " EM_DASH " ", k, sets);
            out_add(num);
            snprintf(stem, sizeof stem, "%s", g_de[i].name);
            sl = strlen(stem);
            stem[sl - 2] = '\0';            /* strip ".c" */
            out_add(stem);
            out_add("\n");
        }
    }

    /* script files */
    out_add("\nSCRIPT FILES (in order):\n");
    for (i = 0; i < n; i++) {
        snprintf(num, sizeof num, "%d. ", i + 1);
        out_add(num);
        out_add(g_de[i].name);
        out_add(g_de[i].isdir ? "/\n" : "\n");
    }

    /* carried-over sections */
    if (join3(rpath, sizeof rpath, fdir, "README.md") != 0)
        bench("readme path over MAXP");
    for (t = 0; t < 3; t++) {
        out_add("\n## ");
        out_add(SEC_TITLE[t]);
        out_add("\n\n");
        if (extract_section(rpath, SEC_TITLE[t], sec, sizeof sec)) {
            if (g_verbose)
                printf("  carry-over: %s <- %s\n", SEC_TITLE[t], fam);
            out_add(sec);
        } else {
            out_add(SEC_PH[t]);
        }
        out_add("\n");
    }

    /* references: tests/ listing */
    out_add("\n## IV. REFERENCES\n\n");
    if (join3(tdir, sizeof tdir, fdir, "tests") != 0)
        bench("tests path over MAXP");
    tn = list_dir(tdir, g_de2, MAXF);
    if (tn <= 0) {
        out_add("(none yet)\n");
    } else {
        out_add("Test samples in tests/, named after the files they came from:\n\n");
        for (i = 0; i < tn; i++) {
            out_add("- ");
            out_add(g_de2[i].name);
            if (g_de2[i].isdir) out_add("/");
            out_add("\n");
        }
    }
    return 1;
}

/* ------------------------------------------------------------------ */
/* Emit g_out: write it, or check it against the existing README.      */
/* Returns 0 identical/written, 1 drift.                               */

static int emit_bytes(const char *path, const char *buf, size_t len,
                      const char *label)
{
    if (g_check) {
        FILE *f = fopen(path, "r");
        size_t i = 0;
        int c, drift = 0;

        if (!f) {
            printf("DRIFT  %s  (missing)\n", label);
            return 1;
        }
        while ((c = fgetc(f)) != EOF) {
            if (i >= len || (unsigned char)c != (unsigned char)buf[i]) {
                drift = 1;
                break;
            }
            i++;
        }
        if (!drift && i != len)
            drift = 1;
        fclose(f);
        printf("%s  %s\n", drift ? "DRIFT " : "IDENT ", label);
        return drift;
    }

    {
        FILE *f = fopen(path, "w");
        if (!f) {
            fprintf(stderr, "WARN: cannot write %s, skipped\n", path);
            return 1;
        }
        if (len && fwrite(buf, 1, len, f) != len) {
            fclose(f);
            fprintf(stderr, "WARN: short write on %s\n", path);
            return 1;
        }
        fclose(f);
    }
    if (g_verbose)
        printf("  wrote %s (%lu bytes)\n", path, (unsigned long)len);
    return 0;
}

static int emit_out(const char *tools_dir, const char *fam)
{
    char fdir[MAXP], rpath[MAXP];

    if (join3(fdir, sizeof fdir, tools_dir, fam) != 0 ||
        join3(rpath, sizeof rpath, fdir, "README.md") != 0)
        bench("readme path over MAXP");
    return emit_bytes(rpath, g_out, g_olen, fam);
}

/* ------------------------------------------------------------------ */

static void usage(void)
{
    fprintf(stderr,
        "usage: shakti-readme-builder TOOLS_DIR [check] [verbose]\n"
        "  check    compare only; exit 4 if any README drifts from canonical\n"
        "  verbose  trace every step\n"
        "  exit 5   naming-law violation (see README RUNNING NOTES)\n");
}

int main(int argc, char **argv)
{
    const char *tools_dir = NULL;
    static char singles[MAXT][MAXN];
    static int  single_ok[MAXT];
    char num[64], mpath[MAXP];
    int i, n, nf = 0, nsingle = 0, nsok = 0;
    int fams = 0, valid = 0, drift = 0;

    for (i = 1; i < argc; i++) {
        if (!strcmp(argv[i], "check"))        g_check = 1;
        else if (!strcmp(argv[i], "verbose")) g_verbose = 1;
        else if (!tools_dir)                  tools_dir = argv[i];
        else { usage(); return 2; }
    }
    if (!tools_dir) { usage(); return 2; }

    n = list_dir(tools_dir, g_de, MAXF);
    if (n < 0) {
        fprintf(stderr, "REFUSE: cannot open %s\n", tools_dir);
        return 2;
    }

    /* split candidates: family dirs vs single-file tools at the root */
    for (i = 0; i < n; i++) {
        if (g_de[i].isdir) {
            if (nf >= MAXT) bench("tool families over MAXT");
            copy_name(g_fams[nf], g_de[i].name);
            nf++;
        } else if (!strncmp(g_de[i].name, "shakti-", 7)) {
            if (nsingle >= MAXT) bench("single-file tools over MAXT");
            copy_name(singles[nsingle], g_de[i].name);
            nsingle++;
        }
    }

    /* pass A: validate names only; nothing emitted yet */
    for (i = 0; i < nf; i++) {
        int r = check_family(tools_dir, g_fams[i]);
        if (r == 1) { g_viol++; g_fam_ok[i] = 0; continue; }
        if (r == 2) { g_fam_ok[i] = 0; continue; }
        g_fam_ok[i] = 1;
        valid++;
    }
    for (i = 0; i < nsingle; i++) {
        if (!valid_single(singles[i])) {
            printf("SKIP %s: naming law — single-file tools are"
                   " shakti-<lowercase-hyphen>\n", singles[i]);
            g_viol++;
            single_ok[i] = 0;
            continue;
        }
        single_ok[i] = 1;
        nsok++;
    }
    if (!valid) {
        fprintf(stderr, "BENCH: no tool families found in %s\n", tools_dir);
        return 3;
    }

    /* master printout: header first, counts fixed by pass A */
    g_mlen = 0;
    g_master[0] = '\0';
    mas_add("# TOOLS MASTER\n\n");
    snprintf(num, sizeof num, "families: %d\n", valid);
    mas_add(num);
    snprintf(num, sizeof num, "single-file tools: %d\n", nsok);
    mas_add(num);
    snprintf(num, sizeof num, "naming violations skipped: %d\n", g_viol);
    mas_add(num);

    /* pass B: emit */
    for (i = 0; i < nf; i++) {
        if (!g_fam_ok[i]) continue;
        if (g_verbose)
            printf("family %s\n", g_fams[i]);
        if (!emit_family(tools_dir, g_fams[i]))
            continue;
        fams++;
        drift += emit_out(tools_dir, g_fams[i]);
        mas_add("\n## family: ");
        mas_add(g_fams[i]);
        mas_add("\n\n");
        mas_addn(g_out, g_olen);
    }
    for (i = 0; i < nsingle; i++) {
        if (!single_ok[i]) continue;
        mas_add("\n## single: ");
        mas_add(singles[i]);
        mas_add("\n\n(1 file at tools root — strict name,"
                " callable from Shakti_Shell)\n");
    }

    if (join3(mpath, sizeof mpath, tools_dir, "TOOLS_MASTER.txt") != 0)
        bench("master path over MAXP");
    drift += emit_bytes(mpath, g_master, g_mlen, "TOOLS_MASTER.txt");

    if (g_verbose || g_check)
        printf("%s: %d famil%s, %d single, %d drifted, %d violations\n",
               g_check ? "check" : "build",
               fams, fams == 1 ? "y" : "ies", nsok, drift, g_viol);
    if (g_viol) return 5;
    if (g_check && drift) return 4;
    return 0;
}
